[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
reduct-rs = "1.7.2"
tokio = { version = "1.33.0", features = ["rt", "rt-multi-thread"] }
bytes = "1.5.0"
futures-util = "0.3.14"